FROM node:22-alpine AS base

WORKDIR /src
COPY package*.json ./

RUN npm install --force

COPY . .

RUN npx prisma db push --schema "./prisma/aihub-database/schema.prisma"
RUN npx prisma db push --schema "./prisma/filenest-database/schema.prisma"
RUN npx prisma db push --schema "./prisma/main-database/schema.prisma"
RUN npx prisma db push --schema "./prisma/telemedicine-database/schema.prisma"

CMD ["npm", "run", "dev"]